Ensure we fail packer jobs if any step fails
Change-Id: If1edd1d8da78880b89937f425e34e29e18deeb81
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>

diff --git a/jjb/releng-macros.yaml b/jjb/releng-macros.yaml
--- a/jjb/releng-macros.yaml
+++ b/jjb/releng-macros.yaml
@@ -461,6 +461,8 @@
               variable: 'CLOUDENV'
       - shell: |
           #!/bin/bash
+          # Ensure we fail the job if any steps fail.
+          set -eu -o pipefail
           cd packer
           varfiles="../packer/vars/*"
           templates="../packer/templates/*"
@@ -487,6 +489,8 @@
               variable: 'CLOUDENV'
       - shell: |
           #!/bin/bash
+          # Ensure we fail the job if any steps fail.
+          set -eu -o pipefail
           cd packer
           export PACKER_LOG="yes" && \
           export PACKER_LOG_PATH="packer-build.log" && \
