Make distribution-check job logic more strict
Multiple build steps use a fake remote repository
in order to discover missing POM references and other failure modes.

Change-Id: I28c2eb56c48fac3953acc0d2dfd858e0a3d914ed
Signed-off-by: Vratko Polak <vratko.polak@gmail.com>

diff --git a/jjb/releng-templates-java.yaml b/jjb/releng-templates-java.yaml
--- a/jjb/releng-templates-java.yaml
+++ b/jjb/releng-templates-java.yaml
@@ -129,7 +129,7 @@
             maven-version: 'mvn33'
 
 - job-template:
-    # Template: {name}-distribution-check-{stream}
+    # Template: {project-name}-distribution-check-{stream}
     # Goal: Build a patch and make sure the distribution can deploy with this change
     # Operation: This job template builds a patch, creates a distribution containing
     #            the patch, and triggers the distribution deploy test
@@ -198,26 +198,101 @@
                 notbuilt: false
 
     builders:
+        # Step zero: Wipe file repositories up front.
+        - shell: |
+            echo "wipe r: the local Maven repository"
+            rm -rfv /tmp/r
+            echo "wipe n: the fake remote (Nexus) repository"
+            rm -rfv /tmp/n
+            echo "wipe t: the transient repository used in some manipulations"
+            rm -rfv /tmp/t
+        # Step one: Online build of the project, using local repository /tmp/r/ and deploying artifacts to /tmp/n/.
+        # Ordinary SingleFeatureTest failures are detected in the verify job, so we can use "q" profile here.
         - maven-target:
             maven-version: 'mvn33'
             pom: '$GERRIT_PROJECT/pom.xml'
-            goals: 'clean install dependency:tree -DoutputFile=dependency_tree.txt -V -B -Pq -Djenkins -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r -Dstream={stream}'
+            goals: 'clean deploy dependency:tree -DoutputFile=dependency_tree.txt -V -B -Pq -Djenkins -Dstream={stream} -DaltDeploymentRepository=fake-nexus::default::file:///tmp/n/ -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r'
             java-opts:
                 - '-Xmx4096m -XX:MaxPermSize=1024m -Dmaven.compile.fork=true'
             settings: '{mvn-settings}'
             settings-type: cfp
             global-settings: 'odl-global-settings'
             global-settings-type: cfp
+        # Step two: Verify all deployed artifacts belong to the project's groupId.
+        # This is done my moving the allowed directories out of /tmp/n and checking no files remained there.
+        # The correct directory is derived from $GERRIT_PROJECT,
+        - shell: |
+            mkdir -p /tmp/t/org/opendaylight/$GERRIT_PROJECT
+            set +e
+            mv /tmp/n/org/opendaylight/$GERRIT_PROJECT/ /tmp/t/org/opendaylight/$GERRIT_PROJECT/
+            set -e
+            test -z `find /tmp/n/ -type f`
+            rm -rf /tmp/n
+            mv /tmp/t /tmp/n
+        # Step three: Online build of integration distribution.
+        # This step is mainly used for downloading other project artifacts.
+        # Running SingleFeaturesTest here does not seem to be required.
         - maven-target:
             maven-version: 'mvn33'
             pom: 'distribution/pom.xml'
-            goals: 'clean install dependency:tree -DoutputFile=dependency_tree.txt -V -B -Djenkins -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r'
+            goals: 'clean install dependency:tree -DoutputFile=dependency_tree.txt -V -B -Pq -Djenkins -Dstream={stream} -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r'
             java-opts:
               - '-Xmx1024m -XX:MaxPermSize=256m -Dmaven.compile.fork=true'
             settings: '{mvn-settings}'
             settings-type: cfp
             global-settings: 'odl-global-settings'
             global-settings-type: cfp
+        # Step four: Delete snapshot artifacts from the local repository.
+        # This is critical to detect orphaned artifacts or missing project-internal dependency declarations.
+        - shell: |
+            set +e  # {project-name}/ may not exist
+            find /tmp/r/org/opendaylight/$GERRIT_PROJECT/ -path *-SNAPSHOT* -delete
+            find /tmp/r/ -name _remote.repositories -delete  # to prevent access to repositories not available in step five
+        # TODO: It is still possible that the project creates and uses artifacts with wrong groupId (without deploying them). Detect that case when it occures.
+        # Now the ugly part. It seems that the only way to tell Maven 2+
+        # which remote repositories to use is via settings.xml file.
+        # So we create such a file here.
+        - shell: |
+            echo '
+            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
+              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
+              https://maven.apache.org/xsd/settings-1.0.0.xsd">
+              <profiles>
+                <profile>
+                  <id>file</id>
+                  <repositories>
+                    <repository>
+                      <id>file</id>
+                      <name>file</name>
+                      <url>file:///tmp/n/</url>
+                      <snapshots/>
+                    </repository>
+                  </repositories>
+                  <pluginRepositories>
+                    <pluginRepository>
+                      <id>file</id>
+                      <name>file</name>
+                      <url>file:///tmp/n/</url>
+                      <snapshots/>
+                    </pluginRepository>
+                  </pluginRepositories>
+                </profile>
+              </profiles>
+            </settings>
+            ' > fake_remotes.xml
+        # Step five: Repeat the distribution build but with the new settings.
+        # Here, only the project snapshot artifacts deployed to /tmp/n are available,
+        # which faithfully reproduces conditions in later verify job runs.
+        # We cannot use --offline, because: "Cannot access file (file:///tmp/n) in offline mode"
+        # This is where SingleFeatureTest are not skipped.
+        - maven-target:
+            maven-version: 'mvn33'
+            pom: 'distribution/pom.xml'
+            goals: 'clean install dependency:tree -DoutputFile=dependency_tree.txt -s fake_remotes.xml -V -B -Pq,file -DskipTests=false -Djenkins -Dstream={stream} -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r'
+            java-opts:
+              - '-Xmx1024m -XX:MaxPermSize=256m -Dmaven.compile.fork=true'
+        # Step six: Run Karaf and verify no critical failures are present.
         - integration-distribution-check
 
     publishers:
@@ -360,6 +435,7 @@
             global-settings-file: 'odl-global-settings'
             settings-file: '{mvn-settings}'
 
+    # TODO: Do we want to apply sophisticated checks as in *-distribution-check-*?
     maven:
         maven-name: 'mvn33'
         goals: '{mvn-goals} -V -B -Djenkins -Dmerge -Dstream={stream} -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r'
