Re-implement loops in integration-copy-ssh-keys
Change-Id: Ia154157c3b4719f6a556eb43ee0dc58a8d84879e
Signed-off-by: Vratko Polak <vrpolak@cisco.com>

diff --git a/jjb/integration/integration-macros.yaml b/jjb/integration/integration-macros.yaml
--- a/jjb/integration/integration-macros.yaml
+++ b/jjb/integration/integration-macros.yaml
@@ -238,23 +238,31 @@
     builders:
         - shell: |
             #!/bin/bash
-            echo "JCLOUDS IPS are ${JCLOUDS_IPS}"
+            echo "Openstack IPs are ${JCLOUDS_IPS}"
 
-            IFS=',' read -ra ADDR <<< "${JCLOUDS_IPS}"
-
-            for j in $(seq 1 30); do
-                if `ssh jenkins@${ADDR[0]} exit`; then
-                    for i in "${ADDR[@]}"; do
+            todo=`echo "${JCLOUDS_IPS}" | tr ',' ' '`
+            for j in `seq 1 30`; do
+                for i in $todo; do
+                    ssh jenkins@${i} exit
+                    err=$?
+                    if [ "$err" == "0" ]; then
                         ssh-copy-id -i /home/jenkins/.ssh/id_rsa.pub "jenkins@${i}" > /dev/null 2>&1
                         ssh jenkins@${i} 'echo "$(facter ipaddress_eth0) $(/bin/hostname)" | sudo tee -a /etc/hosts'
                         echo "Successfully copied public keys to slave ${i}"
-                    done
+                        todo=`echo "${todo/$i}" | xargs`
+                    else
+                        break
+                    fi
+                done
+                if [ "$err" != "0" ]; then
+                        echo "SSH not responding on ${i}. Retrying in 10 seconds..."
+                        sleep 10  # Wait 10 seconds before retrying
+                    continue
+                elif [ -z "${todo-}" ]; then
                     break
-                else
-                    echo "SSH not responding on ${i}. Retrying in 10 seconds..."
-                    sleep 10  # Wait 10 seconds before retrying
                 fi
             done
+            exit $err
 
 # Macro: integration-get-slave-addresses
 # Operation: this macro gets the IP addresses of the dynamic vms
